# Generated by Django 5.0.2 on 2024-03-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtasks',
            old_name='subtask_assigned_user',
            new_name='subtask_collaborators',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_role',
        ),
    ]
