# Generated by Django 5.0.2 on 2024-03-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_customuser_managers_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
