# Generated by Django 5.0.2 on 2024-03-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_user_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task_list',
            name='t_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.task'),
        ),
    ]
