# Generated by Django 5.0.2 on 2024-03-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_user_task_list_t_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
